# Heroku configuration
# From: https://github.com/kissaten/heroku-eureka-server-demo

server.port: ${PORT:8761}

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
