# Heroku configuration
# From: https://github.com/kissaten/heroku-eureka-server-demo

# Stack Overflow:
# https://stackoverflow.com/questions/60414630/problem-with-unknown-ports-on-spring-eureka-client-registration

server.port: ${PORT:8761}

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

bugwars:
  endpoints:
    - "http://bug-wars-ai-crud.herokuapp.com"
    - "http://bug-wars-game-engine.herokuapp.com"
    - "http://bug-wars-api-gateway.herokuapp.com"