# Heroku configuration
# From: https://github.com/kissaten/heroku-eureka-server-demo

server.port: ${PORT:8761}

eureka:
  user: user
  # Set this in Heroku Config Var
  password: password
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.user}:${eureka.password}@${eureka.instance.hostname}:${server.port}/eureka
